cmake_minimum_required(VERSION 3.16)
project(frame_control LANGUAGES C CXX)
set(CMAKE_AUTOMOC ON)
set(CMAKE_CXX_STANDARD 17)
find_package(Qt6 REQUIRED COMPONENTS Widgets DBus)
find_package(KF6GlobalAccel REQUIRED)
find_package(PkgConfig REQUIRED)
pkg_check_modules(SDL3 REQUIRED IMPORTED_TARGET sdl3)
add_executable(frame-control-service controller.cpp)
target_link_libraries(frame-control-service PRIVATE Qt6::Widgets Qt6::DBus KF6::GlobalAccel)
add_executable(frame-input-client client.c)
target_link_libraries(frame-input-client PRIVATE PkgConfig::SDL3)
target_compile_options(frame-input-client PRIVATE -Wall -Wextra -Werror)
target_compile_options(frame-control-service PRIVATE -Wall -Wextra -Werror)
