MODULES=(i2c_qcom_geni gpio_sbu_mux phy_qcom_qmp_combo phy_qcom_qmp_usb phy_qcom_snps_femto_v2 pmic_glink qcom_battmgr pmic_glink_altmode qrtr qcom_pd_mapper qcom_q6v5_pas qcom_glink_smem)
BINARIES=()
FILES=()
HOOKS=(base systemd modconf kms keyboard block filesystems mainframeos-firmware fsck)
COMPRESSION="zstd"
COMPRESSION_OPTIONS=(-T2 -3)
